import pytest
from fastapi.testclient import TestClient
from api.telemetry_server import app, alert_log, add_alert, latest_telemetry_store, vehicle_anchors
import api.telemetry_server as ts
from mapping.living_map import LivingMap
from core.models import SimulatorConditions, VehicleTelemetry, Position
from datetime import datetime, timezone

client = TestClient(app)

@pytest.fixture(autouse=True)
def reset_state():
    alert_log.clear()
    latest_telemetry_store.clear()
    vehicle_anchors.clear()
    
    # Reinitialize living_map with on_alert callback
    ts.living_map = LivingMap(on_alert=add_alert)
    ts.living_map._candidate_routes.clear()
    ts.living_map._load_candidate_routes()
    ts.living_map._last_meaningful_observation_pos.clear()
    
    client.post("/api/simulator/conditions", json={
        "visibility": "CLEAR",
        "road": "DRY",
        "obstacle": "NONE"
    })
    alert_log.clear() # clear alerts generated by the reset
    yield

def test_dashboard_and_strip_endpoints():
    res = client.get("/")
    assert res.status_code == 200
    assert "DRISHTI INTEGRATED DASHBOARD" in res.text

    res = client.get("/strip")
    assert res.status_code == 200
    assert "DRISHTI CAB STRIP" in res.text

def test_simulator_changes_generate_alerts():
    # Trigger FOG
    client.post("/api/simulator/conditions", json={
        "visibility": "FOG",
        "road": "DRY",
        "obstacle": "NONE"
    })
    
    res = client.get("/api/alerts")
    alerts = res.json()
    assert len(alerts) >= 1
    messages = [a["message"] for a in alerts]
    assert "Fog enabled" in messages
    assert "Governor changed to SLOW" in messages

def test_obstacle_generates_stop_alert():
    client.post("/api/simulator/conditions", json={
        "visibility": "CLEAR",
        "road": "DRY",
        "obstacle": "PEDESTRIAN"
    })
    
    res = client.get("/api/alerts")
    alerts = res.json()
    messages = [a["message"] for a in alerts]
    assert "Pedestrian detected" in messages
    assert "Governor changed to STOP" in messages

def test_route_validation_alert():
    vid = "TEST-ALERT-TRUCK"
    
    routes_res = client.get("/api/map/routes")
    routes = routes_res.json()
    if not routes:
        pytest.skip("No demo routes found")
        
    route = routes[0]
    p1 = route["path_coordinates"][0]
    
    # In demo_anchored mode, the first point becomes the anchor and maps to SAR_ANCHOR.
    # To hit p1, we must first send a point at SAR_ANCHOR, so the anchor is SAR_ANCHOR.
    # Then sending p1 will map exactly to p1.
    from core.config import SAR_ANCHOR_LAT, SAR_ANCHOR_LON
    
    # Set anchor
    client.post("/api/telemetry", json={
        "vehicle_id": vid,
        "latitude": SAR_ANCHOR_LAT,
        "longitude": SAR_ANCHOR_LON,
        "altitude": 0,
        "speed_kmh": 0,
        "timestamp": datetime.utcnow().isoformat()
    })
    
    # Point 2 (moves to p1)
    client.post("/api/telemetry", json={
        "vehicle_id": vid,
        "latitude": p1["latitude"],
        "longitude": p1["longitude"],
        "altitude": 0,
        "speed_kmh": 10,
        "timestamp": datetime.utcnow().isoformat()
    })
    
    res = client.get("/api/alerts")
    alerts = res.json()
    messages = [a["message"] for a in alerts]
    
    assert any("Vehicle route validated" in m for m in messages)

def test_alerts_bounded_to_50():
    alert_log.clear()
    for i in range(60):
        add_alert("INFO", f"Test message {i}")
        
    assert len(alert_log) == 50
    # The most recent is at index 0
    assert alert_log[0].message == "Test message 59"

def test_no_duplicate_alerts_on_repeated_polling():
    alert_log.clear()
    # First post
    client.post("/api/simulator/conditions", json={
        "visibility": "FOG",
        "road": "DRY",
        "obstacle": "NONE"
    })
    count_after_first = len(alert_log)
    assert count_after_first > 0
    
    # Second identical post (simulating repeated polling)
    client.post("/api/simulator/conditions", json={
        "visibility": "FOG",
        "road": "DRY",
        "obstacle": "NONE"
    })
    count_after_second = len(alert_log)
    assert count_after_first == count_after_second

def test_multiple_vehicles_and_raw_gps():
    from core.config import SAR_ANCHOR_LAT, SAR_ANCHOR_LON
    
    # Send TRUCK_1
    client.post("/api/telemetry", json={
        "vehicle_id": "TRUCK_1",
        "latitude": 17.0,
        "longitude": 78.0,
        "altitude": 0,
        "speed_kmh": 10,
        "timestamp": datetime.utcnow().isoformat()
    })
    
    # Send TRUCK_2
    client.post("/api/telemetry", json={
        "vehicle_id": "TRUCK_2",
        "latitude": 18.0,
        "longitude": 79.0,
        "altitude": 0,
        "speed_kmh": 20,
        "timestamp": datetime.utcnow().isoformat()
    })
    
    res = client.get("/api/vehicles")
    vehicles = res.json()
    assert len(vehicles) == 2
    
    # Check that original_position exists and matches the raw GPS coordinates sent
    v1 = next(v for v in vehicles if v["vehicle_id"] == "TRUCK_1")
    v2 = next(v for v in vehicles if v["vehicle_id"] == "TRUCK_2")
    
    assert v1["metadata"]["original_position"]["latitude"] == 17.0
    assert v1["metadata"]["original_position"]["longitude"] == 78.0
    
    assert v2["metadata"]["original_position"]["latitude"] == 18.0
    assert v2["metadata"]["original_position"]["longitude"] == 79.0

def test_candidate_routes_provenance():
    res = client.get("/api/map/routes")
    routes = res.json()
    assert len(routes) > 0
    
    for route in routes:
        assert route["source"] in ["DEMO_CANDIDATE", "DEMO VIRTUAL MINE"]
